/** Shared constants: navigation, risk vocabulary and static copy. */

export const APP_NAME = 'LoanLens';
export const APP_TAGLINE = 'Loan agreement analysis';

export const DISCLAIMER =
  'LoanLens is an awareness and screening tool. It does not provide legal advice or determine whether a loan agreement is legally enforceable. Users should consult a qualified professional for legal advice.';

export const SHORT_DISCLAIMER =
  'LoanLens is an awareness and screening tool and does not provide legal advice.';

export const DEMO_NOTICE =
  'These are illustrative demo records generated by LoanLens. They were not produced by a real PDF analysis.';

export const RISK = {
  NORMAL: 'Normal',
  REVIEW: 'Needs Review',
  RISKY: 'Risky'
};

export const RISK_FILTERS = [
  { key: 'All', label: 'All' },
  { key: RISK.NORMAL, label: 'Normal' },
  { key: RISK.REVIEW, label: 'Needs Review' },
  { key: RISK.RISKY, label: 'Risky' }
];

export const RISK_COLORS = {
  Normal: '#16a34a',
  'Needs Review': '#d97706',
  Risky: '#dc2626'
};

export const BAND_COLORS = {
  Low: '#16a34a',
  Medium: '#d97706',
  High: '#dc2626'
};

export const NAV_ITEMS = [
  { to: '/dashboard', label: 'Dashboard', icon: 'LayoutDashboard' },
  { to: '/analyze', label: 'Analyze Document', icon: 'FileSearch' },
  { to: '/agreements', label: 'My Agreements', icon: 'Files' },
  { to: '/reports', label: 'Risk Reports', icon: 'ShieldAlert' },
  { to: '/history', label: 'History', icon: 'History' }
];

export const SECONDARY_NAV = [{ to: '/settings', label: 'Settings', icon: 'Settings' }];

/** Human labels for the analysis pipeline stages returned by the API. */
export const STAGE_LABELS = {
  uploaded: 'Document uploaded',
  extracting: 'Extracting text',
  detecting_structure: 'Detecting document structure',
  segmenting: 'Segmenting clauses',
  analyzing_risk: 'Analyzing risk',
  generating_summaries: 'Generating summaries',
  preparing_report: 'Preparing report'
};

export const MAX_UPLOAD_MB = 20;

export const UPLOAD_RULES = [
  'Only PDF loan agreements are accepted (maximum 20 MB).',
  'Both digital and scanned documents are supported - scanned files go through OCR.',
  'Files stay on your own server; they are never sent to a third party.'
];

export const SORT_OPTIONS = [
  { key: 'recent', label: 'Most recent' },
  { key: 'risk', label: 'Highest risk' },
  { key: 'name', label: 'File name' }
];
